name: EnhancedSurvival
version: 1.0
main: se.joarc.EnhancedSurvival.EnhancedSurvival
api-version: 1.16

commands:
  heal:
    description: Heal and feed yourself
    usage: /heal
  minecartspeed:
    description: Enable creation of speedy-minecarts
    usage: /minecartspeed
  woodtoolcleanup:
    description: Cleanup (Quick-destroy) wood tools (not wooden sword)
    usage: /woodtoolcleanup
  sleepcheck:
    description: Check last slept ticks
    usage: /sleepcheck